;;; opencode-emacs-bridge.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(defvar opencode-emacs-bridge-sessions (make-hash-table :test 'equal) )

(defvar opencode-emacs-bridge-buffer-prefix "*opencode:" )

(defvar opencode-emacs-bridge-command "opencode"
  "Path to the opencode binary.")

(defvar opencode-emacs-bridge-default-model "anthropic/claude-sonnet-4-20250514"
  "Default model for opencode sessions.")

(defvar opencode-emacs-bridge-permission-mode "bypass"
  "Permission mode: bypass or prompt.")

(defun opencode-emacs-bridge--session-get (session-id key)
  "Get KEY from session SESSION-ID."
  (let* ((session (gethash session-id opencode-emacs-bridge-sessions)))
    (when session
    (plist-get session key))))

(defun opencode-emacs-bridge--session-put (session-id key value)
  "Set KEY to VALUE in session SESSION-ID."
  (let* ((session (or (gethash session-id opencode-emacs-bridge-sessions) '())))
    (puthash session-id (plist-put session key value) opencode-emacs-bridge-sessions)))

(defun opencode-emacs-bridge--session-register (session-id props)
  "Register a new session with initial PROPS plist."
  (puthash session-id props opencode-emacs-bridge-sessions))

(defun opencode-emacs-bridge--session-remove (session-id)
  "Remove session SESSION-ID from registry."
  (remhash session-id opencode-emacs-bridge-sessions))

(defun opencode-emacs-bridge--build-env (session-id cwd agent-id)
  "Build process-environment additions for an opencode session."
  (let* ((env (list (format "OPENCODE_SESSION_ID=%s" session-id))))
    (when agent-id
    (setq env (cons (format "CLAUDE_SWARM_SLAVE_ID=%s" agent-id) env))
    (setq env (cons (format "OPENCODE_AGENT_ID=%s" agent-id) env)))
    (when cwd
    (setq env (cons (format "OPENCODE_CWD=%s" cwd) env)))
    env))

(defun opencode-emacs-bridge--build-command (cwd config-dir opts)
  "Build the opencode shell command string.\n   OPTS is a plist with :model, :continue, :session-id, :prompt, :agent."
  (let* ((cmd (list opencode-emacs-bridge-command))
        (model (plist-get opts :model))
        (continue-p (plist-get opts :continue))
        (session (plist-get opts :session-id))
        (prompt-str (plist-get opts :prompt))
        (agent-name (plist-get opts :agent)))
    (when cwd
    (setq cmd (append cmd (list "-c" cwd))))
    (when model
    (setq cmd (append cmd (list "-m" model))))
    (when continue-p
    (setq cmd (append cmd (list "--continue"))))
    (when session
    (setq cmd (append cmd (list "-s" session))))
    (when agent-name
    (setq cmd (append cmd (list "--agent" agent-name))))
    (when prompt-str
    (let* ((prompt-file (make-temp-file "opencode-prompt-" nil ".md")))
    (with-temp-file prompt-file (insert prompt-str))
    (setq cmd (append cmd (list "--prompt" prompt-file)))))
    (mapconcat 'shell-quote-argument cmd " ")))

(defun opencode-emacs-bridge--make-buffer-name (bname)
  "Create buffer name for an opencode session."
  (format "%s%s*" opencode-emacs-bridge-buffer-prefix bname))

(defun opencode-emacs-bridge-spawn (name cwd opts)
  "Spawn an opencode process in a vterm buffer.\n\n   NAME     - Session display name (used for buffer naming)\n   CWD      - Working directory for opencode\n   OPTS     - Plist with optional keys:\n     :model      - LLM model string\n     :agent-id   - Hive agent ID (for swarm integration)\n     :prompt     - System prompt string (written to temp file)\n     :mcp-servers - Extra MCP server alist\n     :continue   - If non-nil, continue last session\n     :session-id - Specific opencode session to resume\n\n   Returns the session-id string."
  (let* ((session-id (or (plist-get opts :agent-id) (format "oc-%s-%d" name (float-time))))
        (agent-id (plist-get opts :agent-id))
        (model (or (plist-get opts :model) opencode-emacs-bridge-default-model))
        (work-dir (or cwd default-directory))
        (buf-name (opencode-emacs-bridge--make-buffer-name name)))
    (require 'opencode-emacs-config)
    (let* ((config-opts (list :model model :agent-id agent-id :mcp-servers (plist-get opts :mcp-servers))))
    (opencode-emacs-config-write-config work-dir config-opts))
    (opencode-emacs-bridge--session-register session-id (list :name name :cwd work-dir :buffer-name buf-name :agent-id agent-id :model model :status 'spawning :created-at (current-time)))
    (let* ((buffer (generate-new-buffer buf-name))
        (env-additions (opencode-emacs-bridge--build-env session-id work-dir agent-id))
        (cmd-str (opencode-emacs-bridge--build-command work-dir work-dir (list :model model :continue (plist-get opts :continue) :session-id (plist-get opts :session-id) :prompt (plist-get opts :prompt) :agent (plist-get opts :agent)))))
    (opencode-emacs-bridge--session-put session-id :buffer buffer)
    (with-current-buffer buffer
    (let* ((default-directory work-dir)
        (process-environment (append env-additions process-environment)))
    (vterm-mode)
    (run-at-time 0.5 nil (lambda (_unused)
    (when (buffer-live-p buffer)
    (with-current-buffer buffer
    (vterm-send-string cmd-str)
    (vterm-send-return))
    (opencode-emacs-bridge--session-put session-id :status 'running))))))
    (display-buffer buffer)
    session-id)))

(defun opencode-emacs-bridge-kill (session-id)
  "Kill the opencode session identified by SESSION-ID.\n   Sends Ctrl-C then kills the buffer."
  (let* ((buffer (opencode-emacs-bridge--session-get session-id :buffer)))
    (when (and buffer (buffer-live-p buffer))
    (with-current-buffer buffer
    (vterm-send-key "c" nil nil t)
    (run-at-time 1.0 nil (lambda (_unused)
    (when (buffer-live-p buffer)
    (kill-buffer buffer))))))
    (opencode-emacs-bridge--session-put session-id :status 'killed)
    (list :killed session-id)))

(defun opencode-emacs-bridge-send (session-id text)
  "Send TEXT to a running opencode session.\n   Useful for dispatching follow-up prompts."
  (let* ((buffer (opencode-emacs-bridge--session-get session-id :buffer)))
    (when (and buffer (buffer-live-p buffer))
    (with-current-buffer buffer
    (vterm-send-string text)
    (vterm-send-return))
    (list :sent t :session-id session-id))))

(defun opencode-emacs-bridge-status (session-id)
  "Return status plist for SESSION-ID."
  (let* ((session (gethash session-id opencode-emacs-bridge-sessions)))
    (when session
    (let* ((buffer (plist-get session :buffer))
        (alive (and buffer (buffer-live-p buffer))))
    (list :session-id session-id :name (plist-get session :name) :status (if alive (plist-get session :status) 'dead) :cwd (plist-get session :cwd) :model (plist-get session :model) :agent-id (plist-get session :agent-id) :buffer-alive alive)))))

(defun opencode-emacs-bridge-list-sessions ()
  "Return a list of all registered session status plists."
  (let* ((result '()))
    (maphash (lambda (id _val)
    (setq result (cons (opencode-emacs-bridge-status id) result))) opencode-emacs-bridge-sessions)
    result))

(defun opencode-emacs-bridge-api-spawn (name presets cwd agent-id)
  "API entry point for hive-mcp swarm.\n\n   Compatible with the hive-mcp-swarm-api-spawn calling convention.\n   NAME      - Agent name\n   PRESETS   - List of preset names (used to build system prompt)\n   CWD       - Working directory\n   AGENT-ID  - Hive agent slave-id\n\n   Returns the session-id."
  (let* ((prompt (when presets
    (condition-case _err
    (when (fboundp 'hive-mcp-swarm-presets-build-system-prompt)
    (hive-mcp-swarm-presets-build-system-prompt presets nil))
  (error nil))))
        (identity-str (format "## YOUR IDENTITY AND ENVIRONMENT\n**Agent ID:** `%s`\n**Working directory:** `%s`\n\n" (or agent-id name) (or cwd default-directory)))
        (full-prompt (if prompt (clel-concat identity-str prompt) identity-str)))
    (opencode-emacs-bridge-spawn name cwd (list :agent-id agent-id :prompt full-prompt))))

(provide 'opencode-emacs-bridge)
;;; opencode-emacs-bridge.el ends here
